# Generated by Django 4.1.2 on 2022-11-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cartorder_cartorderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': '8. Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': '8. Order Items'},
        ),
    ]
