# Generated by Django 4.1.2 on 2022-11-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': '9. Order Items'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': '10. Product Reviews'},
        ),
    ]
