# Generated by Django 4.1.2 on 2022-11-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_cartorderitems_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
    ]
