# Generated by Django 4.1.2 on 2022-11-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_cartorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'In Process'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='process', max_length=150),
        ),
    ]
