# Generated by Django 4.1.2 on 2022-11-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Order Summary',
                'verbose_name_plural': 'orders Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.cartorderitems',),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.BooleanField(default=True),
        ),
    ]
