# Generated by Django 4.1.2 on 2022-11-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_salesummary_alter_cartorder_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Process', 'In Process'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='process', max_length=150),
        ),
    ]
