# Generated by Django 4.1.2 on 2022-11-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_cartorder_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesummary',
            options={'verbose_name': 'Order Summary', 'verbose_name_plural': 'Revenue'},
        ),
    ]
